#!/usr/bin/env python3
"""Fold the homepage into one element that can be pasted into GoHighLevel.

GHL serves no files of its own for a custom-code element, so the stylesheet
and the three scripts are inlined and every image is rewritten to an absolute
URL on the deployed site.

Run from the repo root after changing the site:

    python3 ghl/build-embed.py

Do not hand-edit ghl/portfolio-embed.html. It is output.
"""
import os
import re

BASE = "https://portfolio-website-jeffrey-brianbuilds.vercel.app"
OUT = "ghl/portfolio-embed.html"

html = open("index.html", encoding="utf-8").read()
head = html.split("<head>", 1)[1].split("</head>", 1)[0]

# Every stylesheet the page links, in the page's order, inlined.
css_files = re.findall(r'<link rel="stylesheet" href="(css/[^"?]+)(?:\?[^"]*)?"', head)
assert css_files and css_files[0] == "css/styles.css", css_files
css = "\n\n".join(open(f, encoding="utf-8").read() for f in css_files)

# The original three scripts are inlined, as before.
INLINE = ("main", "sysmap", "gallery")
js = [open(f"js/{n}.js", encoding="utf-8").read() for n in INLINE]

# Everything added since loads from the deployed site instead of being inlined:
# barrel.js and hero-canvas.js are ES modules that resolve their images against
# their own URL (import.meta.url), which only points at the site when the file
# is fetched from it. Head scripts (access.js, intro.js) go first, as on the
# page, so they still run before the body paints.
def external(block):
    out = []
    for tag in re.findall(r'<script [^>]*src="js/[^"]+"[^>]*></script>', block):
        name = re.search(r'src="js/([^"?]+)\.js', tag).group(1)
        if name in INLINE:
            continue
        out.append(tag.replace('src="js/', f'src="{BASE}/js/'))
    return "\n".join(out)
head_js = external(head)
# The body, minus the script tags whose files are being inlined below.
body = html.split("<body>", 1)[1].rsplit("</body>", 1)[0]
body_js = external(body)
body = re.sub(
    r'\n?<!-- [^\n]*?-->\n?<script src="https://go\.jeffreybrianbuilds\.com[^>]*></script>',
    "", body)
body = re.sub(r'\n?<script [^>]*src="js/[^"]+"[^>]*></script>', "", body)
assert not re.search(r'<script [^>]*src=', body), "a <script src> survived into the fragment"

# GHL has nowhere to put an img/ folder.
body, n_img = re.subn(r'(src|href)="(img/[^"]+)"', rf'\1="{BASE}/\2"', body)
assert 'src="img/' not in body and 'href="img/' not in body

# The palette stays on :root. An earlier version also put it on a wrapper class,
# in case GHL scoped the CSS the way its form builder does. It does not, and the
# rewrite turned `:root[data-theme="light"]` into a list starting with a bare
# `:root`, which matches everything: the page came up light over dark cards.
assert ":root {" in css

fragment = f"""<!-- ============================================================
     jeffreybrianbuilds.com as a single GoHighLevel element.

     PASTE INTO A BLANK PAGE. No GHL header, no footer, no other sections.
     This carries its own reset and paints the body, so anything else on the
     page gets restyled by it.

     Images, and the scripts added with the React-branch features (intro,
     accessibility menu, autopilot, barrel, marquee, shader, smooth scroll,
     cursor ring, tab bar), load from {BASE}
     Delete that deployment and they break. To cut the dependency, upload the
     files to GHL's media library and swap the URLs.

     Generated by ghl/build-embed.py. Edit the site, run the script again.
     ============================================================ -->

{head_js}

<style>
@import url("https://fonts.googleapis.com/css2?family=Figtree:wght@400;500;600;700;800&family=Space+Mono:wght@400;700&display=swap");

/* GHL puts page content in a padded, max-width column. The site draws its own
   full-height shell, so it steps out of that column. */
.jbc-site {{
  width: 100vw;
  margin-left: calc(50% - 50vw);
  max-width: none;
}}

{css}
</style>

<div class="jbc-site">
{body.strip()}
</div>

<script>
{js[0]}
</script>
<script>
{js[1]}
</script>
<script>
{js[2]}
</script>
{body_js}
<script>
/* GoHighLevel loads this itself when a page holds a native form or calendar
   element. These are raw iframes so it will not, but if the page does have one,
   loading it twice binds every resize handler twice. */
(function () {{
  var already = Array.prototype.some.call(document.scripts, function (s) {{
    return /form_embed\\.js/.test(s.src || "");
  }});
  if (already) return;
  var s = document.createElement("script");
  s.src = "https://go.jeffreybrianbuilds.com/js/form_embed.js";
  document.body.appendChild(s);
}})();
</script>
"""

os.makedirs("ghl", exist_ok=True)
open(OUT, "w", encoding="utf-8").write(fragment)
print(f"{OUT}: {len(fragment):,} bytes, {n_img} image URLs made absolute")
