#!/usr/bin/env python3
"""Fold each page of the site into one element that can be pasted into GoHighLevel.

The site runs on GoHighLevel as one website page per page here, on
jeffreybrianbuilds.com. A GHL custom-code element holds markup but serves no
files, so every stylesheet, script, image, icon and font is loaded from ASSETS,
the Cloudflare Worker that serves this repo's main branch. That host sends
Access-Control-Allow-Origin for js/, css/ (fonts live in css/fonts/), img/ and
icons/ (see _headers): fonts, module scripts and WebGL textures refuse to load
cross-origin without it.

Run from the repo root after changing the site:

    python3 ghl/build-embed.py

Output goes to ghl/embed/: one .html per page to paste, and PAGES.md, the
checklist of GHL page paths, titles and descriptions. Do not hand-edit it.
"""
import html as html_mod
import os
import re

ASSETS = os.environ.get("GHL_ASSETS", "https://jeffreybrianbuilds.jeffreybriancastro.workers.dev")
OUT_DIR = "ghl/embed"

# Page on disk -> (output name, path of its GHL page on the domain). The four
# walkthroughs keep the paths their GHL pages already have.
PAGES = [
    ("index.html", "home", "/"),
    ("projects.html", "projects", "/projects"),
    ("services.html", "services", "/services"),
    ("testimonials.html", "testimonials", "/testimonials"),
    ("about.html", "about", "/about"),
    ("contact.html", "contact", "/contact"),
    ("book.html", "book", "/book"),
    ("work/automation-workflow.html", "automation-workflow", "/automation-workflow"),
    ("work/ghl-crm-setup.html", "ghl-crm-setup", "/ghl-crm-setup"),
    ("work/sales-funnel.html", "sales-funnel", "/sales-funnel"),
    ("work/website-build.html", "website-build", "/website-build"),
]
SLUG = {src: path for src, _, path in PAGES}
ASSET_DIRS = ("img", "icons", "css", "js")


def ghl_links(markup, src):
    """Point every link between pages at the GHL page that holds it."""
    here = os.path.dirname(src)

    def target(m):
        href = m.group(1)
        path, _, frag = href.partition("#")
        page = os.path.normpath(os.path.join(here, path)) if path else src
        if page not in SLUG:
            return m.group(0)
        url = SLUG[page]
        if frag:
            # Same page: keep the bare anchor so the jump stays in-page.
            url = f"#{frag}" if page == src else f"{url}#{frag}"
        return f'href="{url}"'

    return re.sub(r'href="((?:\.\./)*(?:[a-z-]+/)?[a-z0-9-]+\.html(?:#[^"]*)?)"', target, markup)


def absolute_assets(markup):
    """Root-absolute asset paths (/img/x, /css/x ...) would hit the GHL domain."""
    dirs = "|".join(ASSET_DIRS)
    markup, n = re.subn(rf'((?:src|href|content)=")/(?:{dirs})/', lambda m: m.group(1) + ASSETS + m.group(0)[len(m.group(1)):], markup)
    markup, k = re.subn(rf"url\((['\"]?)/({dirs})/", rf"url(\1{ASSETS}/\2/", markup)
    return markup, n + k


def build(src, name, path):
    page = open(src, encoding="utf-8").read()
    head = page.split("<head>", 1)[1].split("</head>", 1)[0]
    title = re.search(r"<title>(.*?)</title>", head, re.S).group(1).strip()
    desc_m = re.search(r'<meta name="description" content="([^"]*)"', head)
    desc = desc_m.group(1) if desc_m else ""

    # From the head, only what styles and scripts the page: stylesheets and
    # scripts, in the page's own order (theme.js must run before the body).
    head_tags = re.findall(r'<link rel="stylesheet"[^>]*>|<script [^>]*></script>', head)
    assert any("template.css" in t for t in head_tags), src
    body = page.split("<body>", 1)[1].rsplit("</body>", 1)[0]

    head_block, n1 = absolute_assets("\n".join(head_tags))
    body, n2 = absolute_assets(body)
    body = ghl_links(body, src)

    leftover = re.findall(r'href="((?:\.\./)*[^":#]+\.html[^"]*)"', body)
    assert not leftover, f"{src}: unconverted page links {leftover}"
    stray = re.findall(r'(?:src|href)="/(?:img|icons|css|js)/', head_block + body)
    assert not stray, f"{src}: root-relative assets left {stray[:3]}"

    fragment = f"""<!-- ============================================================
     {title}
     GoHighLevel page path: {path}

     PASTE INTO A BLANK PAGE: one Custom Code element, nothing else on it.
     No GHL header, footer or other sections; set the section and row
     padding to 0. This paints the whole page.

     Styles, scripts, fonts, images and icons load from {ASSETS}
     (the Cloudflare Worker serving this repo's main branch). Delete that
     Worker and every page loses its design.

     Layout and look: portfolio-template by BrewedOps (MIT).
     Generated by ghl/build-embed.py. Edit the site, run it again, re-paste.
     ============================================================ -->

{head_block}

<style>
/* GHL puts page content in a padded, max-width column. The site draws its
   own full-viewport shell, so it steps out of that column. */
.jbc-site {{ width: 100vw; margin-left: calc(50% - 50vw); max-width: none; }}
</style>

<div class="jbc-site">
{body.strip()}
</div>
"""
    out = f"{OUT_DIR}/{name}.html"
    open(out, "w", encoding="utf-8").write(fragment)
    print(f"{out}: {len(fragment.encode()) // 1024} KB, {n1 + n2} asset URLs -> {path}")
    return name, path, title, desc


os.makedirs(OUT_DIR, exist_ok=True)
for f in os.listdir(OUT_DIR):
    if f.endswith(".html"):
        os.remove(os.path.join(OUT_DIR, f))
rows = [build(*p) for p in PAGES]

cell = lambda t: html_mod.unescape(t).replace("|", "\\|")
guide = ["# GoHighLevel pages for jeffreybrianbuilds.com", "",
         "Generated by ghl/build-embed.py. One GHL website page per row. For each:",
         "blank page, one Custom Code element, paste the file's whole contents.", "",
         "| Paste this file | GHL page path | SEO title | SEO description |",
         "|---|---|---|---|"]
for name, path, title, desc in rows:
    guide.append(f"| `ghl/embed/{name}.html` | `{path}` | {cell(title)} | {cell(desc)} |")
open(f"{OUT_DIR}/PAGES.md", "w", encoding="utf-8").write("\n".join(guide) + "\n")
print(f"{OUT_DIR}/PAGES.md")
